mainprefix = "z"
prefix = "aet"

name = "AET Auxiliaries Mod"

[properties]
author = "Antistasi Event Team"
url = "https://github.com/Nomas-X/AET_AUX"

[binarize]
enabled = true # Default: true

[files]
include = [
    "mod.cpp",      # These files are copied to the build directory by default
    "meta.cpp",     # They do not need to be added to your list
    "LICENSE",
    "/img/*.paa",
    "logo_ca.paa",
    "logo_co.paa",
	"AETLogo.paa",
	"/assets/*.paa",
    "*.bikey",
    "DiscordRichPresence*.dll"
]
exclude = [
    "*.psd",        # By default this list is empty
    "*.md",
    "/.vscode/",
]

[version]
path = "addons/main/script_version.hpp" # Default
# major = 0 # Overrides path when set
# minor = 1
# patch = 1
# git_hash = 4 # Default: 8